In [14]:
# Dependencies
# ----------------------------------
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:postgres@localhost:5432/Jobs')
connection = engine.connect()

# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base

# Allow us to declare column types
from sqlalchemy import Column, Integer, String, Float 
# Pandas
import pandas as pd

# Matplotlib
import matplotlib.pyplot as plt
from matplotlib import style
style.use('bmh')
# NumPy
import numpy as np

In [15]:
# Query All Records in the Table
indeed_data = pd.read_sql("SELECT * FROM indeed_jobs2", connection)
indeed_data.head()
region_df = pd.read_sql("SELECT * FROM region", connection)
region_df.head()
indeed_data.head()
region_df.head()

        state1 state region
0       Alaska    AK   West
1      Arizona    AZ   West
2   California    CA   West
3     Colorado    CO   West
4       Hawaii    HI   West

In [16]:
region_df['state']=region_df['state'].str.strip()
indeed_data['state']=indeed_data['state'].str.strip()

In [17]:
states = region_df["state"].unique()
states

array(['AK', 'AZ', 'CA', 'CO', 'HI', 'ID', 'MO', 'NV', 'NM', 'OR', 'UT',
       'WA', 'WY', 'IL', 'IN', 'IA', 'KS', 'MI', 'MN', 'NE', 'ND', 'OH',
       'SD', 'WI', 'AL', 'AR', 'DE', 'FL', 'GA', 'KY', 'LA', 'MD', 'MS',
       'OK', 'NC', 'SC', 'TN', 'TX', 'VA', 'WV', 'CT', 'ME', 'NH', 'MA',
       'NJ', 'NY', 'PA', 'RI', 'VT'], dtype=object)

In [26]:
indeed_df = pd.merge(indeed_data, region_df,how="inner",on="state")
indeed_df.head()

,id,company_name,job_summary,job_title,city,state,state1,region
0,2,"Universal Screen Arts, Inc.",Marketing Manager - Print & Data Analytics,Attentive to detail and high level of accuracy...,Hudson,OH,Ohio,Midwest
1,3,Race Winning Brands,Data Analyst,Race Winning Brands is a leader in developing ...,Mentor,OH,Ohio,Midwest
2,4,LeafFilter Gutter Protection,Human Resources Data Analyst - Contract,This is a highly collaborative role where you ...,Hudson,OH,Ohio,Midwest
3,5,T-CETRA LLC,Data Analyst Tier I,We're constantly developing new and creative w...,Dublin,OH,Ohio,Midwest
4,6,Harley-Davidson,Data Analyst,Typically requires a minimum of 3 years of rel...,Valley View,OH,Ohio,Midwest

In [27]:
region = indeed_df["region"].unique()
region

array(['Midwest', 'West', 'South'], dtype=object)

In [28]:
indeed_df[indeed_df["region"] == "West"]
indeed_df.state.dtype
indeed_df['state']=indeed_df['state'].str.strip()
indeed_df['region']=indeed_df['region'].str.strip()

In [29]:
indeed_df[indeed_df["region"] == "West"]

,id,company_name,job_summary,job_title,city,state,state1,region
2180,760,"Amazon Web Services, Inc.",Business Analyst (Start-Ups),Successful candidates will be analytical with ...,Seattle,WA,Washington,West
2181,1306,Continental Mills,Category Management Analyst,5 yearsâ€™ progressive or equivalent working e...,Tukwila,WA,Washington,West
2182,2812,Blue Origin,Cyber Security Analyst III,This team member will serve on a highly experi...,Kent,WA,Washington,West
2183,1562,"Amazon Web Services, Inc.",Operations Analyst,Attention to detail and excellent problem solv...,Seattle,WA,Washington,West
2184,3374,"AMT Medical, Inc.",Quality Engineer,Prepares measurable data for periodic reportin...,Monroe,WA,Washington,West
2185,3717,Novo Nordisk,Data Scientist II Job,The Data Scientist reports to the Head of Digi...,Seattle,WA,Washington,West
2186,1946,Moss Adams,Senior Business Analyst,Minimum of 3 years of relevant experience requ...,Seattle,WA,Washington,West
2187,2076,Solarity Credit Union,Senior Data Analyst,Solarity Credit Union is seeking a Senior Data...,Yakima,WA,Washington,West
2188,2140,Charlie's Produce,Data Visualization Analyst,Charlieâ€™s Produce - Who We Are. Charlie's Pr...,Seattle,WA,Washington,West
2189,2262,Banfield Pet Hospital,"System Analyst, Data & Analytics",The primary purpose and function of the System...,Vancouver,WA,Washington,West
2190,2263,TransWest,Program Manager- Data Analyst,We're looking for an experienced Program Manag...,Seattle,WA,Washington,West
2191,2264,Seen by Indeed,Data Analyst,Seen by Indeed is a free service that connects...,Seattle,WA,Washington,West
2192,2265,Skagit Regional Health,Performance Improvement Data Analyst,Must demonstrate at least 3 years of formal da...,Mount Vernon,WA,Washington,West
2193,2266,"Transaction Network Services, Inc",Data Analyst,The Splunk Analyst is responsible for supporti...,Seattle,WA,Washington,West
2194,2267,Starbucks,"data analyst, Applied Analytics- Seattle, WA","Now Brewing â€“ Data Analyst, Applied Analytic...",Seattle,WA,Washington,West
2195,2268,Neal Analytics,Jr Data Analyst,2 months with the possibility of extension up ...,Redmond,WA,Washington,West
2196,2269,Team Red Dog,Junior Data Analyst,"You want steady income, outstanding benefits a...",Redmond,WA,Washington,West
2197,2270,iconvergence,Data Analyst,"Strong SQL, Excel, Power BI, SSAS. Analyze dif...",Redmond,WA,Washington,West
2198,2271,Oracle,Data Analyst,Detailed Description and Job Requirements. Man...,Seattle,WA,Washington,West
2199,2272,Microsoft,Internship Opportunities for Students: Data & ...,Data Scientists at Microsoft help to improve t...,Redmond,WA,Washington,West
2200,2273,REI,"Data Analyst, Sales and Customer Support Conta...",This entry-level Contact Center Analyst I posi...,Sumner,WA,Washington,West
2201,2274,Starbucks,"data analyst, GSC Metrics & Reporting - Seattl...",This position contributes to Starbucks success...,Seattle,WA,Washington,West
2202,2276,Procter and Gamble,Data Analyst,Do you love diving into data sets? Would you e...,Seattle,WA,Washington,West
2203,2277,Washington Health Benefit Exchange,Data and Reporting Analyst,"Well organized, flexible, proactive, resourcef...",Olympia,WA,Washington,West
2204,2278,Association of Washington Cities,Applications and Data Analyst,The top candidate will be highly motivated and...,Olympia,WA,Washington,West
2205,2279,Fisher Investments,Junior Business Information Analyst (2019-8481),California employees accrue up to 17 days of P...,Camas,WA,Washington,West
2206,2280,Inviso Corporation,Sr Data Analyst â€“ 18 Month Microsoft Contract,Exceptional attention to detail and ability to...,Bellevue,WA,Washington,West
2207,2281,PayScale,Sales Business Intelligence Analyst,Do you have that curious analytical mind with ...,Seattle,WA,Washington,West
2208,2282,Indeed,Business Intelligence Analyst,"As the worldâ€™s number 1 job site, our missio...",Seattle,WA,Washington,West
2209,2283,eXcell,"Data Analyst - Power BI, SQL",Did you know that Gartner positioned eXcell as...,Redmond,WA,Washington,West
...,...,...,...,...,...,...,...,...
4872,5005,"Amazon.com Services, Inc.","Software Development Engineer, Amazon SageMake...","With Amazon SageMaker, Amazon Web Service's (A...",Seattle,WA,Washington,West
4873,5006,Deloitte,AI/ML Cloud Deployment Engineer- Senior Engineer,"Knowledge of machine learning, information ret...",Seattle,WA,Washington,West
4874,5007,Deloitte,AI/ML Cloud Deployment EngineerÂ - Senior Arch...,"Knowledge of machine learning, information ret...",Seattle,WA,Washington,West
4875,5008,"Amazon.com Services, Inc.","Principal Product Manager - Technical, Compute...","Working knowledge of deep learning, machine le...",Seattle,WA,Washington,West
4876,5009,Amazon Services LLC,Senior Software Development Engineer - Deep Le...,"Hands-on experience with machine learning, dee...",Seattle,WA,Washington,West
4877,5010,red violet,Data Scientist,"Degree in Computer Science, Machine Learning, ...",Seattle,WA,Washington,West
4878,5011,Abstract Tokenization,Data Scientist,Experience creating and using advanced machine...,Seattle,WA,Washington,West
4879,5012,Solarity Credit Union,Senior Data Analyst,If you are an individual with a disability and...,Yakima,WA,Washington,West
4880,5013,Tredence Inc.,Data Scientist / Data Analytics,Our capabilities range from Data Visualization...,Seattle,WA,Washington,West
4881,5014,Porch,Senior Data Scientist,You should have extensive experience with data...,Seattle,WA,Washington,West
4882,5015,Tesla,Data Scientist/Machine Learning Engineer,We are looking for a Sr Data Scientist to help...,Seattle,WA,Washington,West
4883,5016,Amazon Services LLC,Senior Software Development Engineer - Deep Le...,"Hands-on experience with machine learning, dee...",Seattle,WA,Washington,West
4884,5017,Porch,Lead Data Scientist,"Manage a team of data scientists, potentially ...",Seattle,WA,Washington,West
4885,5018,Allstate,Senior Data Scientist - Experimental Design,Utilizes effective project planning techniques...,Bothell,WA,Washington,West
4886,5019,Indeed,Senior Data Scientist,The base salary range below represents the low...,Seattle,WA,Washington,West
4887,5020,Jobot,Data Scientist,Our ideal candidate will come from an industri...,Spokane,WA,Washington,West
4888,5021,eXcell,Database Engineer / Data Scientist,We are looking for seasoned engineers with str...,Redmond,WA,Washington,West
4889,5022,Law Dawgs,In-House Data Privacy Counsel,"Implement, support and report on data privacy ...",Seattle,WA,Washington,West
4890,5023,Nestle USA,Sr. Customer Data Analyst,Intermediate understanding of the R language.D...,Seattle,WA,Washington,West
4894,5028,Mayo Clinic,"Tableau Desktop, Data Mining/Machine, Python, ...",Business Intelligence Analyst,Scottsdale,AZ,Arizona,West
4895,5029,Intel,Data modelling and managing data.Generally we ...,Data Scientist,Phoenix,AZ,Arizona,West
4896,5030,"Master Electronics, Inc.","Extensive Python experience using Sci-Kit, Ten...",Data Scientist,Phoenix,AZ,Arizona,West
4897,5031,ViaSat,"Experience in data cleansing, statistics/machi...",Industrial Engineer - Data Scientist,Tempe,AZ,Arizona,West
4898,5033,"Master Electronics, Inc.",Master Electronics has an exciting career oppo...,Data Scientist,Phoenix,AZ,Arizona,West
4899,5034,American Express,"Spark, Splunk, Pandas, Numpy, Sci-kit learn.Th...",Fullstack Engineer- Machine Learning,Phoenix,AZ,Arizona,West
4900,5035,American Express,"Spark, Splunk, Pandas, Numpy, Sci-kit learn.Th...",Engineer- Python & Machine Learning,Phoenix,AZ,Arizona,West
4901,5036,Carvana,Design large relational data sets from unstruc...,Data Science Engineer,Tempe,AZ,Arizona,West
4902,5037,Intel,"Data Science and Statistics tools (Python, Num...",Equipment Development Engineer,Phoenix,AZ,Arizona,West
4903,5038,ViaSat,"Experience in data cleansing, statistics/machi...",Industrial Engineer - Data Scientist,Tempe,AZ,Arizona,West
4904,5039,Trilogy Ed,Trilogy Education partners with universities t...,Web Development Teaching Assistant - Universit...,Gilbert,AZ,Arizona,West

In [34]:
states = indeed_df["state"].unique()
states

array(['OH', None, 'WA', 'CA', 'MA', 'NY'], dtype=object)

In [4]:
job_title = indeed_df["job_title"].unique()
job_title

array(['Marketing Manager - Print & Data Analytics', 'Data Analyst',
       'Human Resources Data Analyst - Contract', 'Data Analyst Tier I',
       'Data Analyst II, Hudson OH',
       'Data Analyst-Medical Records/Health Analytics',
       'HR Administration Data Analyst', 'Data Analyst I, II, III',
       'Entry Level Business Analyst', 'Jr. Business Analyst',
       'Data Analyst (Bilingual Spanish)', 'IT Business Analyst',
       'IT Data Analyst Professional Apprentice®',
       'Data Analyst (all levels)', 'Data Analyst, Pricing',
       'Flight Data Analyst', 'Financial Data Analyst',
       'Insight/Data Analyst', 'Data Science Intern - Global Technology',
       'IT / Business Analyst', 'Entry Level Data Analyst',
       'SAP Master Data Analyst', 'Business Analyst',
       'Manager - Business Analyst and Process Improvement',
       'Genetic Data Analyst', 'Quality Data Analyst',
       'Supply Chain Data Analyst', 'Data Science Internship',
       'Business Analyst I - Kronos', 'Marketing Data Analyst',
       'Client Success Data Analyst (CSDA)',
       'Data Scientist/ Statistician Intern (BS/MS Students)',
       'Business Analyst I', 'Intern - Data Analytics',
       'Associate Data Analyst, Operational Analytics',
       'Data Analyst Internship', 'Master Data Analyst I',
       'IDQ Data Analyst', 'Data Analyst Associate',
       '(Remote) Business/Data Analyst', 'Data Analyst Senior',
       'Data Analyst I', 'Data Analyst to Data Analyst Sr',
       'Data Analytics Specialist',
       'Data Analyst - Passenger Transportation', 'Data Analyst 1',
       'Business Analyst - Summer 2020 Internship',
       'Financial/Business Analyst 4', 'Business Analyst- Operations',
       'Business Analyst - Operations',
       'Urgent Need - Data Analyst - Mason OH',
       'Sr. Store Development Data Analyst',
       'Product Development Data Analyst',
       'Business Analyst [Cleveland, OH]', 'Program Data Analyst',
       '2020 Summer Internship - Bank Supervision/Data Science',
       'Data/Business Analyst',
       'Urgent Need - Business Analyst- Mason OH', 'Sr. Business Analyst',
       'Healthcare Data Analyst', 'Data Analyst Lead',
       'Data Analytics Consultant',
       'Financial Crimes Advisory Associate (Data Analytics)',
       'Mortgage Business Analyst', 'Sr. Business Data Analyst',
       'Data Analytics Intern - Summer 2020',
       'Junior IT Business Analyst', 'Data Analyst- Power BI',
       'Data Analytics Intern',
       'Sr. Data Analyst (with Business Intelligence Experience)',
       'Business Analyst – Sales & Product Management',
       'Summer 2020 Internship Program - Data Science',
       'Associate Data Analyst',
       'Intern, Information Services - Data Science',
       'Intern- Data Scientist', 'AIC Intern- Data Analysis and Research',
       'Business Analyst Consultant', 'District Business Analyst',
       'Data Analyst - UC Health Victory Parkway', 'IT Data Analyst',
       'Data Scientist/ Statistican Intern (PhD Level)',
       'Senior Data Analyst', 'Business Analyst - Accenture CAS',
       'Data Analyst/Data Modeler - Based in Cincinnati, OH',
       'Intern, Market Development Organization - Data Science',
       'Lead Data Analyst', 'Jr. Project Manager / Business Analyst',
       'Data Analyst - Tier 1', 'Financial Business Analyst III',
       'Campus Recruiting - Business Analyst/ Process Analyst',
       'Operations Business Analyst', 'Data Science Intern (Summer 2020)',
       'Intern, Business Analyst - IS', 'Data Analyst (Quality Control)',
       'IT Business Analyst / Quality Assurance Testing (#65434)',
       'Agile Business Analyst', 'Clinical Quality Data Analyst',
       'Claims Encounter Data Analyst',
       'Senior Business Intelligence & Data Science Analyst',
       'Business Analyst (Sales)', 'Junior Business Analyst',
       'Senior Business Analyst', 'Business Data Analyst',
       'RDC Data Analyst- Research Information Services',
       'DBA/ Data Analyst', 'Director, Measurement & Data Analytics',
       'System Data Analyst', 'Sr. Data Analyst',
       'Senior Health Data Analyst', 'Lab Technician / Data Analyst',
       'Data Analyst, Predictive Modeling',
       'CCB - Risk Analytics - Customer Risk Data Analyst - Associate',
       'Business Analyst-Office of Opioid Safety',
       'Data Science Intern - Global HQ', 'Business Analyst - Finance',
       'Oracle Finance/Hyperion Business Analyst II',
       'Talent Acquisition Data Analyst Intern (Part-Time)',
       'Physician Services Data Analyst', 'EMPI Data Analyst',
       'HR Business Analyst',
       'Project Management Analyst (Data Analytics/Qlikview)',
       'Senior Healthcare Data Analyst',
       'Business Analyst, IT Product Development',
       'IT Business Analyst (Global Support)',
       'Business Analyst /Lens Category Analyst - Mason OH',
       'Business Analyst, Order Management/RPA',
       'Sr. Data Analyst - Tableau Dashboard Develope',
       'Data Analyst 4 (Government)',
       'Business Analyst (SAP Manufacturing)',
       'Business Analyst - Business Intelligence',
       'Senior IT Business Analyst (#65472)',
       'Data & Finance Business Analyst',
       'Data Scientist-Master’s Degree Internship',
       'Business Analyst # JN -102019-49595', 'Billing Business Analyst',
       'Associate Business Analyst', 'Data Analyst Senior to Lead',
       'Sr. IT Business Analyst', 'SAP FICO Business Analyst',
       'Business Analyst - ERP Data Management',
       'Salesforce Business Analyst',
       'CCB - Home Lending - Data Analyst - Associate',
       'CCB - Quantitative Modeling/Data Science Associate',
       'Manager, Business Analyst', 'Business Analyst II',
       'Associate Director (Data Science & Advanced Analytics)',
       'Japanese Bilingual Business Analyst', 'Tableau Business Analyst',
       'Data Scientist Associate, Workforce Analytics',
       'Associate Business Analyst - Business Analyst & Insight - Full Time - Days',
       'Data Scientist Graduate Intern (Summer 2020)',
       'Customer Business Analyst - Kroger - Cincinnati',
       'Senior Analyst - Logistics Data Analyst', 'Business Analyst / PM',
       'Senior IT Business Analyst (Kofax Kapow RPA)',
       'Specialist, IT & Data Analysis',
       '2020 Summer Internship Program – Business Analyst/Project Management (Cincinnati)',
       'Cash Management Business Analyst', 'IT Business Analyst III',
       'Data Science & Analytics Intern - Summer 2020',
       'Business Analyst - Medicaid Systems',
       'Oracle EBS ( Mfg) Business Analyst /Oracle EBS ( Mfg) BA',
       'Client Business Analyst', 'P&C Business Analyst Intern',
       'Technical Business Analyst', 'Transportation Business Analyst',
       'Business Analyst / Quality Assurance Specialist',
       'Business Analyst-Data Governance', 'Business Analyst- Cincinnati',
       'AML Operations Support Sr. Business Analyst – Ops Intel',
       'Business Analyst 2', 'Business Analyst- IS Project Mgmt Office',
       'Senior Data Analyst/ETL Developer',
       'Asset Management, Global Sales Enablement, Business/Data Analyst - Associate',
       'Business Analysts',
       'Commercial Excellence Data Analyst Spring Co-op',
       'Sales Operations Business Analyst',
       'Sr. Analyst, Data Analytics and Visualization',
       'IT Business Analyst, eCommerce', 'Data Analyst Developer, Senior',
       'IT Business Analyst - Process Manufacturing',
       'Senior IT Business Analyst (Kronos/Payroll Time and Attendance Application)',
       'SAP FI/CO Senior Business Analyst',
       'CCB – Data Management - Risk Data Analyst - Vice President',
       'CRA Logistics Data Analyst', 'Oracle Business Analyst',
       'IT Product Owner/Business Analyst',
       'Business Analyst, Concept to Customer Space',
       'IT Business Analyst II', 'IT\xa0Business Analyst Co-op',
       'Technology Business Analyst - Corporate Technology',
       'Sr. Business Analyst II',
       'Fincl Ctrl Business Anlyst Assc - Financial Controls Business Analyst',
       'Business Analyst - Digitial Products - Software Engineering Firm',
       'Operations Performance Business Analyst- Excel reporting',
       'Commercial Excellence Data Analyst Summer Co-op',
       'Operations Performance Business Analyst-Excel Reporting',
       'HEDIS Data Analyst - Quality Improvement - Full Time - Days',
       'IT Business Analyst - Tax Applications',
       'Business Analyst/Category Manager',
       'Agile Product Owner, Business Analyst, Office of the General Counsel - AVP',
       'Business Analyst (Legal)', 'SAP Business Analyst',
       'Business Analyst Specialist Sr – IT',
       'Analytics Business Analyst', 'Sr. Business Analyst with Power BI',
       'Lead IT Business Analyst (BRM)', 'Business Analyst/Developer',
       'Explainable Artificial Intelligence and Topological Data Analysis (Full-Time)',
       'Technical Business Analyst - SaaS Implementations',
       'Senior Marketing Data Analyst',
       'Explainable Artificial Intelligence and Topological Data Analysis (Part-Time)',
       'Senior Associate, Federal Data Analyst',
       'Sr Business Analyst - Process Improvement',
       'Network Admin with Business Analyst',
       'Senior Professional Business Analyst',
       'Data Analytics / Internal Audit Manager',
       'SAP Plant Maintenance/Materials Management Business Analyst',
       'Lead Business Analyst in Cleveland Area',
       'Business Analyst/Project Manager',
       'Business Analyst - COMMANDbatch Insights',
       'Pharmacy Systems Coordinator and Data Analyst',
       'Business Analyst - Contact Center', 'Business Analyst/Associate',
       'Report Writer Business Analyst - Information Technology',
       'Sr Business Analyst – (BA5) Posting ID 65784 Posted On 09/30/2019',
       'Business Analyst III',
       'Senior Business Analyst - Medicaid Systems',
       'Product Business Analyst Lead', 'MDM Business Analyst II',
       'Data Scientist-PhD Internship',
       'Summer 2020 Internship Program - IT Marketing/API Technology (Business Analyst)',
       'Sr IT Business Analyst - Refining Applications',
       'Wealth Management, Investment Middle Office, Business Analyst, Associate',
       'Data Analyst Lead- Columbus, OH (LOCAL CANDIDATES ONLY)',
       'Business Analyst/Project Manager - Global Financial Services & Systems',
       'Senior Business Analyst (Sales team)',
       'Data Analytics Business Consultant Technical',
       'Sr Salesforce Business Analyst', 'Sr Business Analyst (Zelle)',
       'Senior Business Analyst(Consumer Collections)',
       'Fintech Senior Business Analyst',
       'Consumer & Market Knowledge - Data Analytics Manager (Experienced)',
       'IT - Business Analyst II-IV',
       'Capital Markets Lead Business Analyst',
       'IT Marketing Business Analyst',
       'Tech Business Analyst - Claims Editing',
       'LOB Senior Business Analyst',
       'Sr. Business Analyst /Scrum Master - Top Financial Institution',
       'Media Data Analytics and Insights Manager - Personal Health Care',
       'Pricing and Credit Business Analyst Sr. – Vehicle Finance',
       'Insurance LOB Lead Business Analyst.',
       'Business Analyst - IT Finance',
       'Director, Digital Media Analytics & Data Science',
       'IT Supply Chain Business Analyst',
       'Senior Associate, Federal Business Analyst',
       'Sr. Manager, Lead Business Analyst', 'Senior Business Analysts',
       'SAP Functional Business Analyst',
       'Salesforce Senior Business Analyst-H&PS - Accenture Technology',
       'Senior Consultant, Advanced Analytics (Sr. Cloud Data Engineer- AAA)',
       'EHS Compliance and Data Analytics Specialist - Middletown, CT',
       'Senior Business Analyst - Foreign Military Sales',
       'Sr. Consultant, FinancialForce PSA Business Analyst',
       'Material Handling Data Engineer', 'Data Engineer',
       'AIP Intern-Investment Data Engineer',
       'Data Science Software Engineer - Entry Level',
       'Data Engineer Intern', 'Data Engineer -- Data Curation',
       'Staff Data Engineer', '(MW) Data Engineer',
       'Data Engineer -- Tabular Model', 'Data Analytics Engineer',
       'Advisor, Data Engineer', 'Business Analyst (Start-Ups)',
       'Mid-Level Data Science Software Engineer', 'Senior Data Engineer',
       'Azure Data Engineer', 'Cyber Data Scientist I',
       'Big Data Engineer', 'Data Engineer / EDW', 'Data Scientist',
       'Data Engineer Sr', 'Senior Data Scientist, Digital',
       'Data Engineer Specialist', 'Data Engineer – Data and Insights',
       'Cloud/Data Engineer', 'Data Scientist/Engineer',
       'Java/Hadoop Developer OR Big Data Engineer',
       'Sr Data Engineer- Self Service',
       'Lead Health Data Science Assets',
       'Staff Quality Engineer -Data Analytics', 'Data Scientist 2',
       'Contract – Cloud Data Engineer – hourly rate open based on qualifications',
       'Sr Staff Data Engineer',
       'Data Scientist/Statistician (PhD Level)',
       'Sr. Big Data Engineer (Hadoop)',
       'Big Data Engineer - Project Delivery Specialist',
       'Data Engineer-DB', 'Data Scientist-R&D', 'Staff Data Scientist',
       'Cloud Architect/Data Engineer', 'Lead Data Engineer',
       'AWS Data Engineer', 'Associate Data Scientist*',
       'Citizen Data Scientist', 'Data Scientist I',
       'Data Scientist - Ph.D.', 'Data Scientist, Telematics',
       'Machine Learning Data Scientist', 'NLP Data Scientist',
       'Data Scientist.', 'Data Scientist-Master’s Degree',
       'Data Scientist - Supply Chain', 'Data Scientist II',
       'Commercial Lines Insurance Data Scientist (Actuary) #85988',
       'Data Scientist Senior or Lead', 'Senior Data Scientist',
       'Data Scientist - Machine Learning Architect',
       'Data Scientist-Masters', 'Experienced Data Scientist',
       'Finance Data Scientist', 'Cognitive Data Scientist (668388)',
       'Data Scientist Computer Vision',
       'Marketing Campaign Analytics Data Scientist - Consumer Bank',
       'Sr. Health Care Data Scientist - 8+ Years', 'Data Scientist III',
       'Open Source Data Scientist, Mid', 'Data Scientist-PhD Degree',
       'Data Scientist/Solution Architect',
       'Data Science Research Associate',
       'Data Scientist II - RI Solutions & Innovations',
       'Data Science Co-op (Spring 2020)', 'Director of Data Science',
       'CCB - Quantitative Modeling/Data Science - Vice President',
       'Lead Data Scientist - Healthcare',
       'Commercial Banking –Executive Director - Data Science, Analytics & Insights',
       'Senior Data Scientist - Insurance',
       'Test & Control Data Scientist-PhD Degree',
       'Consultant, Operations Research & Data Science',
       'CDC Data Science Fellowship',
       'Data Science Researcher I/II Dayton, OH - ACL',
       '(Project Staff) Specialist, Data Science',
       'Engagement Manager / Lead Data Scientist',
       'Venture Leader – Data Science & AI',
       'STUDENT II - Zacharias Lab (Developmental Biology) - Computer/Data Science Majors',
       'Project Staff, Data Science Technology Implementation Specialist',
       'Hi-Tech Industry –AI/Data Science/Deep Machine Learning Senior Manager',
       'Program Manager- Data Analyst',
       'Performance Improvement Data Analyst', 'Jr Data Analyst',
       'Junior Data Analyst',
       'Data Analyst, Sales and Customer Support Contact Center',
       'Applications and Data Analyst',
       'Sr Data Analyst – 18 Month Microsoft Contract',
       'Data Analyst - Power BI, SQL', 'Sales Operations Data Analyst',
       'Data Science & Analytics Intern (Paid) - Summer 2020',
       'French language Data Analyst', 'Product Analyst, Data Science',
       'Strategic Data Analyst (Mgmt Sys Anlyst) - Temporary',
       'SQL Data Analyst', 'Hydro Data Analyst',
       'Digital Business Analyst', 'Business Analyst-Contracts Analyst',
       'Data Analyst (2019-8385)', 'Project Consulting & Data Analyst',
       'Data Science Analyst', 'Business Data Analyst (Entry Level)',
       'Sr. Customer Data Analyst',
       'Data Analyst (SQL, PowerBI) Corp-corp is also fine',
       'Healthcare Management Data Analyst',
       'Data Analyst II/III (Machine Learning)',
       'T&D Asset Management Data Analyst',
       'Clinical Data Analyst Trauma',
       'Senior Business Analyst, US Trend Monitoring & Reporting',
       'Technology Business Analyst (2019-8213)',
       'Data Analyst / Data Applied Scientist',
       'Search Engine Data Analyst', 'Systems Data Analyst',
       'Director of Data Science and Analytics',
       'Data Scientist - Intern', 'Investment Data Analyst',
       'HR Business Data Analyst', 'Data Analyst IV',
       'Data Analyst, Data & Analytics (Advanced Analytics) Manager (Multiple Positions)',
       'Senior Business Analyst, Data Strategy and Reporting',
       'Senior Game Data Analyst - Turn 10 Studios',
       'Security Data Analyst II', 'Intern Data Scientist',
       'Data Analyst (Ad-Hoc Reporting)',
       'Product Analyst/Business Analyst Intern, Summer 2020',
       'Data Analyst Transcription', 'Data Analyst Sr',
       'Software Data Analyst Intern – Part-Time',
       'Data Scientist Intern, PhD, 2020',
       'Research and Data Analyst, Malaria and Neglected Tropical Diseases',
       'Product Owner / Business Analyst', 'Construction Data Analyst',
       'Business Analyst 3337~',
       'Data & Analytics Business Analyst / Data Modeler',
       'Data Analyst, Sales Enablement', 'Staff Quality Data Analyst',
       'FinTech Compliance Data Analyst', 'Market Research Data Analyst',
       'Data Analyst / Business Analyst',
       'Transportation Analyst/Data Scientist', 'Technical Data Analyst',
       'Sr. Data Analyst*', 'Data Analyst, Tax Technology',
       'Health Integration Data Analyst',
       'Data Science (Telematics) Intern',
       'Data Analyst (IoT Connected Products)',
       'Data Analytics Project Manager',
       'Program Analyst – Data Analytics Support',
       'Data Analyst, Marketing', 'Business Analyst, Air',
       'Business Analyst, Asian Markets', 'Data Science Intern',
       'HDQC Digital Content Data Analyst', 'Data Analyst II',
       'Data Analyst (Report Automation & Delivery)',
       'Business Analyst, w/Investment Management exp.',
       'ERC Business Analyst', 'Data Analyst II / Business Analyst',
       'Business Analyst - HCM',
       'Data Analyst II (Healthcare Analytics) - West',
       'Senior Data Analyst - Health Care Innovation',
       'CORE - Data Analyst', 'Salesforce Data Analyst',
       'Data Analyst, Senior - Research', 'Business Analyst eBusiness',
       'Senior Analyst, Data Science and Analytics',
       'Business Analyst III - Financial Systems Group',
       'Business Analyst, SCAR team supporting Global Specialty Fulfillment',
       'Business Analyst, Requirements',
       'Payments Business Analyst ( Spanish )',
       'Cloud Business Analyst/Strategist',
       'Senior Data Analyst (Local Candidates Only)',
       'Business Analyst, Employee Experience',
       'Business Analyst, Food Operations',
       'Business Analyst, Alexa Skills',
       'Internship – Multiple Locations – Data Analytics',
       'Business Analyst, NASCO',
       'Payments Business Analyst ( Portuguese )',
       'Business Analyst, MFN RCX', 'Data Science Research Internship',
       'Business Analyst - Sustainability',
       'Product Owner/Business Analyst, Agile',
       'Business Analyst, Seller Experience', 'Business Analyst II, TOM',
       'Data Analytics and Insights Consultant',
       'Business Analyst, AWS IQ',
       'Business Analyst, Selling Partner Abuse',
       'Business Analyst CA Media', 'Computer Systems Business Analyst 1',
       'IT Business Analyst Intern', 'Computer or Business Analyst',
       'Business Analyst, SCAR',

In [5]:
states_grouped = indeed_df.groupby("state")
states_grouped.count()

       company_name  job_summary  job_title  city   id
state
 CA             664          664        664   664  664
 MA              50           50         50    50   50
 NY             175          175        175   175  175
 OH             627          627        627   627  627
 WA             880          880        880   880  880

In [8]:
indeed_df[indeed_df["state"] == "NY"]

Empty DataFrame
Columns: [company_name, job_summary, job_title, city, state, id]
Index: []